# Jobs Configuration File - New Modular System
# This file has been restructured for better maintainability
# Each job now has its own configuration file in the jobs/ folder

# IMPORTANT: This configuration now uses separate files for each job
# Individual job files are located in: src/main/resources/jobs/
# - miner.yml        (Miner job configuration)
# - lumberjack.yml   (Lumberjack job configuration)  
# - farmer.yml       (Farmer job configuration)
# - hunter.yml       (Hunter job configuration)
# - fisherman.yml    (Fisherman job configuration)
# - builder.yml      (Builder job configuration)

# The new system automatically loads from jobs_index.yml
# This provides better organization and easier maintenance for developers

# Benefits of the new system:
# ✅ Each job has its own file - easier to edit and maintain
# ✅ Developers can work on different jobs without conflicts
# ✅ Better organization and modular structure
# ✅ Easier to add new jobs - just create a new file
# ✅ Backward compatibility maintained

# Migration Notice:
# All job configurations have been separated into individual files
# Job loading is controlled by jobs_index.yml (use_separate_files: true)

# Legacy jobs configuration (kept for backward compatibility)
# This section will not be used when use_separate_files=true in jobs_index.yml
jobs:
  # This section is now deprecated in favor of separate job files
  # To revert to the old system, set use_separate_files: false in jobs_index.yml
  # Then you can add job configurations here in the old format